// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msgproto is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Msg
*/
package msgproto

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Msg struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Lat              *int64 `protobuf:"varint,2,req,name=lat" json:"lat,omitempty"`
	Long             *int64 `protobuf:"varint,3,req,name=long" json:"long,omitempty"`
	Utime            *int64 `protobuf:"varint,4,req,name=utime" json:"utime,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}

func (m *Msg) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Msg) GetLat() int64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *Msg) GetLong() int64 {
	if m != nil && m.Long != nil {
		return *m.Long
	}
	return 0
}

func (m *Msg) GetUtime() int64 {
	if m != nil && m.Utime != nil {
		return *m.Utime
	}
	return 0
}

func init() {
}
