// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package hacktohell.org.bustrcker_client;

public final class msgproto {
  private msgproto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:msgproto.msg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required int64 lat = 2;</code>
     */
    boolean hasLat();
    /**
     * <code>required int64 lat = 2;</code>
     */
    long getLat();

    /**
     * <code>required int64 long = 3;</code>
     */
    boolean hasLong();
    /**
     * <code>required int64 long = 3;</code>
     */
    long getLong();

    /**
     * <code>required int64 utime = 4;</code>
     */
    boolean hasUtime();
    /**
     * <code>required int64 utime = 4;</code>
     */
    long getUtime();
  }
  /**
   * Protobuf type {@code msgproto.msg}
   */
  public static final class msg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:msgproto.msg)
      msgOrBuilder {
    // Use msg.newBuilder() to construct.
    private msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final msg defaultInstance;
    public static msg getDefaultInstance() {
      return defaultInstance;
    }

    public msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lat_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              long_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              utime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hacktohell.org.bustrcker_client.msgproto.internal_static_msgproto_msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hacktohell.org.bustrcker_client.msgproto.internal_static_msgproto_msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hacktohell.org.bustrcker_client.msgproto.msg.class, hacktohell.org.bustrcker_client.msgproto.msg.Builder.class);
    }

    public static com.google.protobuf.Parser<msg> PARSER =
        new com.google.protobuf.AbstractParser<msg>() {
      public msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LAT_FIELD_NUMBER = 2;
    private long lat_;
    /**
     * <code>required int64 lat = 2;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 lat = 2;</code>
     */
    public long getLat() {
      return lat_;
    }

    public static final int LONG_FIELD_NUMBER = 3;
    private long long_;
    /**
     * <code>required int64 long = 3;</code>
     */
    public boolean hasLong() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 long = 3;</code>
     */
    public long getLong() {
      return long_;
    }

    public static final int UTIME_FIELD_NUMBER = 4;
    private long utime_;
    /**
     * <code>required int64 utime = 4;</code>
     */
    public boolean hasUtime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 utime = 4;</code>
     */
    public long getUtime() {
      return utime_;
    }

    private void initFields() {
      id_ = 0;
      lat_ = 0L;
      long_ = 0L;
      utime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLong()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUtime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, lat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, long_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, utime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, lat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, long_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, utime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hacktohell.org.bustrcker_client.msgproto.msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(hacktohell.org.bustrcker_client.msgproto.msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code msgproto.msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:msgproto.msg)
        hacktohell.org.bustrcker_client.msgproto.msgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hacktohell.org.bustrcker_client.msgproto.internal_static_msgproto_msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hacktohell.org.bustrcker_client.msgproto.internal_static_msgproto_msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hacktohell.org.bustrcker_client.msgproto.msg.class, hacktohell.org.bustrcker_client.msgproto.msg.Builder.class);
      }

      // Construct using hacktohell.org.bustrcker_client.msgproto.msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        long_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        utime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hacktohell.org.bustrcker_client.msgproto.internal_static_msgproto_msg_descriptor;
      }

      public hacktohell.org.bustrcker_client.msgproto.msg getDefaultInstanceForType() {
        return hacktohell.org.bustrcker_client.msgproto.msg.getDefaultInstance();
      }

      public hacktohell.org.bustrcker_client.msgproto.msg build() {
        hacktohell.org.bustrcker_client.msgproto.msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hacktohell.org.bustrcker_client.msgproto.msg buildPartial() {
        hacktohell.org.bustrcker_client.msgproto.msg result = new hacktohell.org.bustrcker_client.msgproto.msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.long_ = long_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.utime_ = utime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hacktohell.org.bustrcker_client.msgproto.msg) {
          return mergeFrom((hacktohell.org.bustrcker_client.msgproto.msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hacktohell.org.bustrcker_client.msgproto.msg other) {
        if (other == hacktohell.org.bustrcker_client.msgproto.msg.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLong()) {
          setLong(other.getLong());
        }
        if (other.hasUtime()) {
          setUtime(other.getUtime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLong()) {
          
          return false;
        }
        if (!hasUtime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hacktohell.org.bustrcker_client.msgproto.msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hacktohell.org.bustrcker_client.msgproto.msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private long lat_ ;
      /**
       * <code>required int64 lat = 2;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 lat = 2;</code>
       */
      public long getLat() {
        return lat_;
      }
      /**
       * <code>required int64 lat = 2;</code>
       */
      public Builder setLat(long value) {
        bitField0_ |= 0x00000002;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 lat = 2;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lat_ = 0L;
        onChanged();
        return this;
      }

      private long long_ ;
      /**
       * <code>required int64 long = 3;</code>
       */
      public boolean hasLong() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 long = 3;</code>
       */
      public long getLong() {
        return long_;
      }
      /**
       * <code>required int64 long = 3;</code>
       */
      public Builder setLong(long value) {
        bitField0_ |= 0x00000004;
        long_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 long = 3;</code>
       */
      public Builder clearLong() {
        bitField0_ = (bitField0_ & ~0x00000004);
        long_ = 0L;
        onChanged();
        return this;
      }

      private long utime_ ;
      /**
       * <code>required int64 utime = 4;</code>
       */
      public boolean hasUtime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 utime = 4;</code>
       */
      public long getUtime() {
        return utime_;
      }
      /**
       * <code>required int64 utime = 4;</code>
       */
      public Builder setUtime(long value) {
        bitField0_ |= 0x00000008;
        utime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 utime = 4;</code>
       */
      public Builder clearUtime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        utime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:msgproto.msg)
    }

    static {
      defaultInstance = new msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:msgproto.msg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_msgproto_msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_msgproto_msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\010msgproto\";\n\003msg\022\n\n\002id\030\001 \002(\005" +
      "\022\013\n\003lat\030\002 \002(\003\022\014\n\004long\030\003 \002(\003\022\r\n\005utime\030\004 \002" +
      "(\003B+\n\037hacktohell.org.bustrcker_clientB\010m" +
      "sgproto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_msgproto_msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_msgproto_msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_msgproto_msg_descriptor,
        new java.lang.String[] { "Id", "Lat", "Long", "Utime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
